# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ebebworkspace
# "service" is the name of this project. This will also be added to your AWS resource names.
service: spotiyCoverAPI
frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  httpApi:
    cors: true

functions:
  getimage:
    handler: bootstrap
    memorySize: 256
    timeout: 10
    environment:
      ${file(token.yml):}
    events:
      - httpApi:
          path: /getimage
          method: post